tenants:
  datasources:
    vw:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: 'jdbc:mysql://localhost:3306/vw'
      username: 'root'
      password: ''
    bmw:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: 'jdbc:mysql://localhost:3306/bmw'
      username: 'root'
      password: ''
    toyota:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: 'jdbc:mysql://localhost:3306/toyota'
      username: 'root'
      password: ''